// Code generated by meta. DO NOT EDIT.

package example

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewAMao,
	NewAMaoWithGreetImpl,
	NewBarAOPWithBye,
	NewBarAOPWithGreet,
	NewDefaultBar,
	NewDefaultFoo,
	NewFooAOPWithBye,
	NewFooAOPWithGreet,

	wire.Bind(new(AMaoForGreet), new(*AMao)),
	NewAMaoIfaceWithProxyImpl,
	wire.Bind(new(AMaoIfaceForProxy), new(*AMaoWithGreetImpl)),
	wire.Bind(new(AMaoIface), new(*AMaoIfaceWithProxyImpl)),
	wire.Bind(new(BarAOPForGreet), new(*Bar)),
	wire.Bind(new(BarAOPForBye), new(*BarAOPWithGreetImpl)),
	NewBarIfaceWithProxyImpl,
	wire.Bind(new(BarIfaceForProxy), new(*BarAOPWithByeImpl)),
	wire.Bind(new(BarIface), new(*BarIfaceWithProxyImpl)),
	wire.Bind(new(FooAOPForGreet), new(*Foo)),
	wire.Bind(new(FooAOPForBye), new(*FooAOPWithGreetImpl)),
	NewFooIfaceWithProxyImpl,
	wire.Bind(new(FooIfaceForProxy), new(*FooAOPWithByeImpl)),
	wire.Bind(new(FooIface), new(*FooIfaceWithProxyImpl)),
)

type AMaoIfaceForProxy AMaoIface

type AMaoIfaceWithProxyImpl struct {
	AMaoIface
}

func NewAMaoIfaceWithProxyImpl(_proxy AMaoIfaceForProxy) *AMaoIfaceWithProxyImpl {
	_proxyImpl := &AMaoIfaceWithProxyImpl{
		AMaoIface: _proxy,
	}
	_proxy.SetSelf(_proxyImpl)
	return _proxyImpl
}

type BarIfaceForProxy BarIface

type BarIfaceWithProxyImpl struct {
	BarIface
}

func NewBarIfaceWithProxyImpl(_proxy BarIfaceForProxy) *BarIfaceWithProxyImpl {
	_proxyImpl := &BarIfaceWithProxyImpl{
		BarIface: _proxy,
	}
	return _proxyImpl
}

type FooIfaceForProxy FooIface

type FooIfaceWithProxyImpl struct {
	FooIface
}

func NewFooIfaceWithProxyImpl(_proxy FooIfaceForProxy) *FooIfaceWithProxyImpl {
	_proxyImpl := &FooIfaceWithProxyImpl{
		FooIface: _proxy,
	}
	return _proxyImpl
}
