// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gomelon/autowire/testdata/example"
)

// Injectors from wire.go:

func initApp(barGreeting example.BarGreeting, barBye example.BarBye, fooGreeting example.FooGreeting, fooBye example.FooBye) (*App, error) {
	foo := example.NewDefaultFoo()
	fooAOPWithGreetImpl := example.NewFooAOPWithGreet(foo, fooGreeting)
	fooAOPWithByeImpl := example.NewFooAOPWithBye(fooAOPWithGreetImpl, fooBye)
	fooIfaceWithProxyImpl := example.NewFooIfaceWithProxyImpl(fooAOPWithByeImpl)
	bar := example.NewDefaultBar()
	barAOPWithGreetImpl := example.NewBarAOPWithGreet(bar, barGreeting)
	barAOPWithByeImpl := example.NewBarAOPWithBye(barAOPWithGreetImpl, barBye)
	barIfaceWithProxyImpl := example.NewBarIfaceWithProxyImpl(barAOPWithByeImpl)
	aMao := example.NewAMao()
	aMaoWithGreetImpl := example.NewAMaoWithGreetImpl(aMao)
	aMaoIfaceWithProxyImpl := example.NewAMaoIfaceWithProxyImpl(aMaoWithGreetImpl)
	app := NewApp(fooIfaceWithProxyImpl, barIfaceWithProxyImpl, aMaoIfaceWithProxyImpl)
	return app, nil
}
